### ISSUE TITLE
Swap time selector and buttons

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-Dev/swx_geospace#3]
- [x] Buttons on right, time range on left.
- [ ] Obtain feedback from forecasters. 
- [ ] Document. 
- [ ] Decide what we keep.

**Comment by joeschoonover** [comment]
Do we want to change the scope of this issue ?

**Comment by MicheleCash** [comment]
Possibly. I might say that we keep it like this for a while and then see what the forecasters think. Can we move this to a "Waiting" or something else since it is not actively being worked?
